// Curated knowledge catalog. Each skill key maps to an ordered list of topics
// spanning Foundation → Intermediate → Advanced, plus a project. The roadmap
// generator slices these into phases; unknown skills fall back to the generic
// template generator so unlimited custom tracks still produce real roadmaps.

const t = (name, description, difficulty, minutes, concepts, exercises, project, success) => ({
  name,
  description,
  difficulty,
  minutes,
  concepts,
  exercises,
  project: project || null,
  success: success || [],
})

export const CATALOG = {
  Python: [
    t('Python fundamentals & data types', 'Variables, basic data types, control flow and how Python programs are structured.', 'beginner', 45,
      ['Variables & naming', 'Strings, integers, floats, booleans', 'Lists, tuples, dicts, sets', 'if/elif/else', 'for & while loops'],
      ['Write a script that classifies a list of numbers (even/odd/prime)', 'Build a simple text menu using loops and conditionals']),
    t('Functions & error handling', 'Writing reusable functions, arguments, return values and handling exceptions.', 'beginner', 45,
      ['Defining & calling functions', 'Args, kwargs, default values', 'Return values & scope', 'try/except/else/finally', 'Raising custom exceptions'],
      ['Refactor a flat script into functions', 'Add robust error handling to a user-input program']),
    t('Working with files & data', 'Reading and writing files, working with JSON/CSV and basic data pipelines.', 'beginner', 45,
      ['open/read/write', 'CSV with the csv module', 'JSON serialization', 'Pathlib basics'],
      ['Parse a CSV log and produce summary stats', 'Read/write a JSON config file']),
    t('Modules, packages & environments', 'Organizing code into modules, virtual environments and package management.', 'beginner', 40,
      ['Import system', '__main__ guard', 'Standard library tour', 'venv & pip', 'requirements.txt'],
      ['Split a program into multiple modules', 'Create a venv and install a package']),
    t('Intermediate: comprehensions & functional patterns', 'Idiomatic Python — comprehensions, map/filter, lambdas and generators.', 'intermediate', 50,
      ['List/dict/set comprehensions', 'map, filter, zip', 'Lambdas', 'Generators & yield', 'sorted with keys'],
      ['Rewrite loops as comprehensions', 'Build a lazy generator pipeline for a large dataset']),
    t('Object-oriented Python', 'Classes, inheritance, dunder methods and writing maintainable object models.', 'intermediate', 60,
      ['Classes & instances', 'Instance/class methods', 'Inheritance & composition', 'Dunder methods', 'Properties & dataclasses'],
      ['Model a small domain (e.g. library or e-commerce) with classes', 'Use dataclasses to reduce boilerplate']),
    t('Working with REST APIs in Python', 'Making HTTP requests, authenticating, parsing JSON and handling errors.', 'intermediate', 60,
      ['HTTP methods & status codes', 'requests library', 'Headers & query params', 'Authentication (API keys, tokens)', 'JSON parsing & error handling', 'Rate limits & retries'],
      ['Call a public API (e.g. Open-Meteo or JSONPlaceholder)', 'Parse JSON and handle non-200 responses', 'Build a small API client with retries'],
      'Build a CLI that pulls data from an API and saves a report.'),
    t('Automation with Python', 'Automating repetitive tasks — files, web, email and scheduled scripts.', 'intermediate', 60,
      ['os/shutil automation', 'Globbing & batch file ops', 'Scheduling (cron / schedule lib)', 'Web scraping basics (BeautifulSoup)', 'Sending emails / notifications'],
      ['Automate renaming/organizing a folder of files', 'Scrape a page and extract structured data']),
    t('Testing & debugging', 'Writing tests with pytest and debugging effectively.', 'intermediate', 50,
      ['pytest basics', 'Fixtures & parametrize', 'Assertions & mocking', 'pdb & logging', 'Test coverage'],
      ['Write tests for a function you wrote earlier', 'Use a debugger to fix an intentional bug']),
    t('Advanced: concurrency & performance', 'Threads, async/await and making Python programs faster.', 'advanced', 70,
      ['Threading vs asyncio', 'async/await', 'ThreadPoolExecutor', 'Profiling & bottlenecks', 'Caching (lru_cache)'],
      ['Speed up API calls with asyncio', 'Profile a script and optimize the hot path']),
    t('Advanced: design patterns & architecture', 'Applying proven patterns and structuring larger Python applications.', 'advanced', 70,
      ['Factory & strategy patterns', 'Decorators in depth', 'Context managers', 'Dependency injection', 'Layering & separation of concerns'],
      ['Refactor code to use a strategy pattern', 'Write a reusable context manager']),
    t('Capstone: Python automation project', 'Build a complete automation solution using everything learned.', 'advanced', 180,
      ['Requirements & design', 'Implementation', 'Error handling & logging', 'Testing', 'Documentation'],
      ['Design the project scope', 'Implement the core logic', 'Add tests and docs'],
      'Build an end-to-end automation tool: e.g. a data pipeline that pulls an API, transforms data, writes a report, and emails it on a schedule.'),
  ],

  SQL: [
    t('SQL basics: SELECT & filtering', 'Querying tables, filtering rows and sorting results.', 'beginner', 40,
      ['SELECT & columns', 'WHERE & operators', 'ORDER BY & LIMIT', 'DISTINCT', 'NULL handling'],
      ['Write queries against a sample database', 'Filter and sort a dataset']),
    t('Aggregation & grouping', 'GROUP BY, aggregate functions and HAVING.', 'beginner', 45,
      ['COUNT, SUM, AVG, MIN, MAX', 'GROUP BY', 'HAVING vs WHERE', 'CASE expressions'],
      ['Compute per-group statistics', 'Write a CASE-based report']),
    t('JOINs', 'Combining tables with INNER, LEFT, RIGHT and FULL joins.', 'intermediate', 60,
      ['INNER JOIN', 'LEFT/RIGHT JOIN', 'FULL OUTER JOIN', 'Self joins', 'Multiple joins', 'Join vs subquery'],
      ['Join customers to orders', 'Find records present in one table but not another']),
    t('Subqueries & CTEs', 'Nested queries, common table expressions and window functions.', 'intermediate', 60,
      ['Scalar & correlated subqueries', 'EXISTS / IN', 'WITH (CTE)', 'Window functions (ROW_NUMBER, RANK)'],
      ['Refactor a query to use a CTE', 'Rank rows with window functions']),
    t('Database design & normalization', 'Modeling data, keys and normalization.', 'intermediate', 55,
      ['Primary & foreign keys', 'Normal forms (1NF–3NF)', 'Indexes', 'Constraints'],
      ['Design a schema for a business domain', 'Normalize a denormalized table']),
    t('Advanced SQL patterns', 'Performance, transactions and advanced query techniques.', 'advanced', 70,
      ['Query planning & EXPLAIN', 'Indexing strategy', 'Transactions & isolation', 'Recursive CTEs', 'Pivoting'],
      ['Optimize a slow query', 'Write a recursive CTE (e.g. org hierarchy)']),
    t('Capstone: SQL analytics project', 'Build a reporting/analytics solution with SQL.', 'advanced', 150,
      ['Schema design', 'ETL queries', 'Reporting views', 'Optimization'],
      ['Design and load a schema', 'Create analytical reports'],
      'Build an analytics pipeline: load a dataset, model it, and produce a set of business reports.'),
  ],

  JavaScript: [
    t('JavaScript fundamentals', 'Core language: types, functions, control flow and scope.', 'beginner', 45,
      ['Variables (let/const)', 'Data types & coercion', 'Functions & arrows', 'Conditionals & loops', 'Scope & closures'],
      ['Write small functions', 'Work with arrays and objects']),
    t('Arrays, objects & the DOM', 'Manipulating data and the browser DOM.', 'beginner', 50,
      ['Array methods (map/filter/reduce)', 'Object spread & destructuring', 'DOM selection & events', 'Templates literals'],
      ['Build an interactive to-do list', 'Transform data with array methods']),
    t('Async JavaScript', 'Promises, async/await and fetching data.', 'intermediate', 60,
      ['Callbacks vs promises', 'async/await', 'fetch & APIs', 'Error handling', 'Event loop basics'],
      ['Fetch data from an API and render it', 'Handle loading/error states']),
    t('ES modules & tooling', 'Modules, bundlers and npm.', 'intermediate', 45,
      ['import/export', 'npm & package.json', 'Bundlers (Vite/Webpack)', 'ESLint'],
      ['Split code into modules', 'Add a build step to a small project']),
    t('Advanced JS patterns', 'Closures in depth, prototypes, and modern patterns.', 'advanced', 60,
      ['Closures & IIFE', 'Prototypes & classes', 'this binding', 'Generators', 'Symbols'],
      ['Implement a small library', 'Solve tricky closure problems']),
    t('Capstone: JavaScript application', 'Build a complete client-side application.', 'advanced', 180,
      ['Architecture', 'State management', 'Async data', 'Polish'],
      ['Plan the app', 'Implement features', 'Handle async data'],
      'Build an interactive web app (e.g. a dashboard or game) using vanilla JS and a public API.'),
  ],

  'REST APIs': [
    t('HTTP & REST fundamentals', 'How HTTP and RESTful design work.', 'beginner', 45,
      ['HTTP methods & status codes', 'Resources & URIs', 'Request/response', 'Headers', 'JSON'],
      ['Inspect requests in a tool', 'Design a resource model']),
    t('Designing REST APIs', 'Resource modeling, routes and conventions.', 'intermediate', 60,
      ['Resource naming', 'Nested resources', 'Versioning', 'Query params & filtering', 'HATEOAS basics'],
      ['Design endpoints for a domain', 'Document with examples']),
    t('Authentication & security', 'Securing APIs with tokens, keys and OAuth.', 'intermediate', 60,
      ['API keys', 'Bearer tokens', 'OAuth2 & scopes', 'Rate limiting', 'CORS'],
      ['Secure an endpoint', 'Implement a rate limit']),
    t('Building & testing APIs', 'Implementing and validating an API end to end.', 'advanced', 90,
      ['Implementation', 'Validation & error formats', 'Testing (Postman / code)', 'Pagination'],
      ['Build a small API', 'Write tests'],
      'Build a small REST API with auth and pagination, and test it.'),
  ],

  'Git/GitHub': [
    t('Git basics', 'Version control fundamentals and local workflow.', 'beginner', 40,
      ['init, add, commit', 'status, log, diff', 'Branches & checkout', 'merge', 'gitignore'],
      ['Initialize and commit a project', 'Create and merge a branch']),
    t('Collaborating with GitHub', 'Remotes, pull requests and code review.', 'intermediate', 50,
      ['clone, push, pull', 'Forks & remotes', 'Pull requests', 'Code review', 'Issues'],
      ['Push to a remote', 'Open and review a PR']),
    t('Advanced Git', 'Rebasing, stashing and recovering work.', 'advanced', 50,
      ['rebase vs merge', 'stash', 'reflog & recovery', 'Cherry-pick', 'Submodules'],
      ['Clean up history with rebase', 'Recover a lost commit']),
  ],

  AI: [
    t('AI fundamentals', 'Core concepts: ML, neural networks and how models learn.', 'beginner', 50,
      ['What is ML/AI', 'Supervised vs unsupervised', 'Training vs inference', 'Neural networks', 'Common terminology'],
      ['Describe how a model learns', 'Classify problem types']),
    t('Working with LLMs', 'Prompting, context and building on large language models.', 'intermediate', 60,
      ['LLMs & tokens', 'Prompt engineering', 'Context windows', 'Temperature & sampling', 'Hallucinations & limitations'],
      ['Write effective prompts', 'Compare outputs across strategies']),
    t('Building AI applications', 'RAG, agents and production AI systems.', 'advanced', 90,
      ['Retrieval-augmented generation', 'Embeddings & vector search', 'Function calling', 'Agents & tools', 'Evaluation'],
      ['Build a RAG pipeline', 'Design an agent with tools'],
      'Build a small AI-powered application (e.g. a Q&A assistant over documents).'),
  ],

  'AI Agents': [
    t('Agent fundamentals', 'What agents are and how they differ from chat models.', 'beginner', 45,
      ['Agent anatomy', 'Planning & acting', 'Tools & function calling', 'Memory', 'Evaluation'],
      ['Design a simple agent flow']),
    t('Building agentic workflows', 'Multi-step reasoning, tool use and orchestration.', 'intermediate', 60,
      ['ReAct-style loops', 'Tool selection', 'State & memory', 'Retries & error handling'],
      ['Implement a tool-using loop']),
    t('Multi-agent systems', 'Coordinating multiple agents and robustness.', 'advanced', 90,
      ['Orchestration patterns', 'Agent roles', 'Handoffs', 'Evaluation & safety'],
      ['Design a multi-agent system', 'Add guardrails'],
      'Build a small multi-agent workflow that completes a task end to end.'),
  ],

  Automation: [
    t('Automation fundamentals', 'Identifying what to automate and core patterns.', 'beginner', 40,
      ['What to automate', 'Scripts vs tools', 'Triggers & scheduling', 'Error handling', 'Logging'],
      ['Identify a manual task to automate', 'Write a simple automation script']),
    t('Automating systems', 'APIs, files, web and cross-system automation.', 'intermediate', 60,
      ['API automation', 'File & email automation', 'Web automation', 'Integrations'],
      ['Automate a multi-step task']),
    t('Robust automation', 'Reliability, monitoring and orchestration.', 'advanced', 90,
      ['Idempotency', 'Retries & backoff', 'Monitoring', 'Scheduling at scale'],
      ['Harden an automation', 'Add monitoring'],
      'Build a reliable end-to-end automation with retries and logging.'),
  ],

  Azure: [
    t('Azure fundamentals', 'Cloud concepts and core Azure services.', 'beginner', 45,
      ['Cloud models', 'Core services (compute, storage, networking)', 'Regions & availability', 'Resource groups', 'Pricing basics'],
      ['Map core services to use cases']),
    t('Azure administration', 'Identity, resources and management.', 'intermediate', 60,
      ['Entra ID & RBAC', 'VMs & App Services', 'Storage accounts', 'Monitoring', 'ARM/Bicep'],
      ['Deploy a resource', 'Configure RBAC']),
    t('Azure architecture', 'Designing resilient, secure Azure solutions.', 'advanced', 90,
      ['Well-Architected Framework', 'Networking & security', 'Scaling', 'Cost optimization'],
      ['Design a solution architecture'],
      'Design and deploy a multi-resource Azure solution.'),
  ],

  PowerShell: [
    t('PowerShell fundamentals', 'Shell basics, cmdlets and the pipeline.', 'beginner', 45,
      ['Cmdlets', 'The pipeline', 'Objects', 'Variables & operators', 'Help system'],
      ['Write simple pipelines', 'Explore the help system']),
    t('Scripting with PowerShell', 'Scripts, functions and error handling.', 'intermediate', 60,
      ['Scripts & functions', 'Parameters', 'Error handling', 'Modules', 'Remoting'],
      ['Write a reusable function', 'Automate a task']),
    t('Advanced PowerShell', 'Automating Microsoft services and robust scripts.', 'advanced', 90,
      ['Microsoft Graph calls', 'Scheduled jobs', 'Advanced pipeline', 'Logging'],
      ['Automate an admin task'],
      'Build a script that automates a Microsoft 365 / Azure admin workflow.'),
  ],

  'Business Analysis': [
    t('BA fundamentals', 'Role, techniques and stakeholder engagement.', 'beginner', 45,
      ['BA role & value', 'Stakeholder identification', 'Elicitation techniques', 'Requirements types'],
      ['Identify stakeholders', 'Draft elicitation questions']),
    t('Requirements & modeling', 'Capturing and modeling requirements.', 'intermediate', 60,
      ['User stories & acceptance criteria', 'Use cases', 'Process modeling', 'Data requirements', 'Prioritization'],
      ['Write user stories', 'Model a process']),
    t('Solution assessment', 'Validating and improving solutions.', 'advanced', 60,
      ['Gap analysis', 'Impact analysis', 'Success metrics', 'Continuous improvement'],
      ['Run a gap analysis'],
      'Produce a full requirements package for a sample initiative.'),
  ],

  'Project Management': [
    t('PM fundamentals', 'Core project management concepts and lifecycle.', 'beginner', 45,
      ['Project lifecycle', 'Scope, time, cost', 'Stakeholders', 'Risk basics'],
      ['Define a project charter']),
    t('Planning & execution', 'Plans, scheduling and execution.', 'intermediate', 60,
      ['Work breakdown structure', 'Scheduling & dependencies', 'Resource planning', 'Tracking & reporting'],
      ['Build a WBS and schedule']),
    t('Agile & leadership', 'Agile practices and team leadership.', 'advanced', 60,
      ['Scrum & Kanban', 'Sprints & retrospectives', 'Leadership & communication', 'Risk management'],
      ['Run a retrospective'],
      'Plan and simulate delivery of a small project.'),
  ],

  ServiceNow: [
    t('ServiceNow fundamentals', 'Platform concepts and navigation.', 'beginner', 45,
      ['Platform overview', 'Tables & records', 'Navigation & lists', 'Forms & fields', 'Users & roles'],
      ['Navigate and query records']),
    t('ITSM & CMDB', 'Core ITSM processes and the configuration management database.', 'intermediate', 60,
      ['Incident, problem, change', 'Service catalog', 'CMDB & CI classes', 'Discovery basics'],
      ['Model CIs', 'Configure a catalog item']),
    t('ServiceNow scripting', 'Client/server scripting and automation.', 'intermediate', 60,
      ['Server-side scripting (Business Rules, Script Includes)', 'Client scripts & UI policies', 'GlideRecord & GlideAjax', 'Flows'],
      ['Write a business rule', 'Automate with Flow Designer']),
    t('Integrations & architecture', 'REST APIs and platform architecture.', 'advanced', 90,
      ['REST API & integrations', 'Web services', 'Performance & best practices', 'Governance'],
      ['Build an integration'],
      'Build an end-to-end ServiceNow integration with a scripted REST API.'),
  ],

  'Solution Architecture': [
    t('Architecture fundamentals', 'What architects do and core design principles.', 'beginner', 45,
      ['Role & mindset', 'Requirements → architecture', 'Trade-offs', 'Views & viewpoints'],
      ['Summarize an architecture']),
    t('Architecture patterns', 'Common patterns and styles.', 'intermediate', 60,
      ['Layered, microservices, event-driven', 'Integration patterns', 'Security architecture', 'Non-functional requirements'],
      ['Choose patterns for a scenario']),
    t('Designing solutions', 'End-to-end solution design and communication.', 'advanced', 90,
      ['Solution design process', 'Documentation & diagrams', 'Cost & scalability', 'Decision records'],
      ['Design a solution'],
      'Produce a solution architecture document for a sample business problem.'),
  ],
}

// Generic fallback for skills/tracks not in the catalog. Produces a real,
// structured, actionable roadmap using the goal's own name as the subject.
export function genericTopics(goalName) {
  const s = goalName.trim()
  return [
    t(`Introduction to ${s}`, `Orientation: what ${s} is, why it matters, and the core terminology you need to start.`, 'beginner', 40,
      [`What is ${s}?`, 'Why it matters for your goals', 'Core terminology', 'The big picture / mental model'],
      [`Write a short summary of ${s} in your own words`, `List 5 real-world applications of ${s}`]),
    t(`${s} fundamentals`, `The foundational concepts and building blocks every ${s} practitioner must master.`, 'beginner', 45,
      ['Core concepts & principles', 'Key components', 'Basic workflow / process', 'Common tools'],
      ['Complete a guided fundamentals exercise', 'Explain the core concepts back']),
    t(`Core concepts of ${s}`, 'Deepening your grasp of the most important ideas and how they fit together.', 'beginner', 50,
      ['Concept interconnections', 'Standard conventions', 'Common pitfalls'],
      ['Apply concepts to a worked example', 'Identify pitfalls in a sample']),
    t(`Intermediate ${s} patterns`, 'Moving beyond basics: patterns, techniques and best practices.', 'intermediate', 60,
      ['Common patterns', 'Best practices', 'Intermediate techniques', 'Tooling'],
      ['Implement a pattern', 'Refactor a basic solution to follow best practices']),
    t(`Working with ${s} in practice`, 'Applying ${s} to realistic, hands-on scenarios.', 'intermediate', 60,
      ['Realistic scenario walkthrough', 'Edge cases', 'Quality & verification'],
      ['Solve a realistic scenario', 'Handle an edge case']),
    t(`Advanced ${s} techniques`, 'Advanced topics that separate proficient practitioners from experts.', 'advanced', 75,
      ['Advanced techniques', 'Performance & optimization', 'Design trade-offs'],
      ['Implement an advanced technique', 'Optimize an existing solution']),
    t(`Real-world ${s} scenarios`, 'Tackling complex, real-world problems with ${s}.', 'advanced', 75,
      ['Complex scenario analysis', 'Decision making', 'Integration with other areas'],
      ['Work through a complex scenario']),
    t(`Capstone: ${s} project`, `Build a practical project that demonstrates your ${s} skills end to end.`, 'advanced', 180,
      ['Planning & requirements', 'Implementation', 'Testing & polish', 'Documentation'],
      ['Scope the project', 'Implement it', 'Test and document'],
      `Build a complete ${s} project that you could show to demonstrate real competence.`),
  ]
}
